### ISSUE TITLE
[Bug] Feline crashes

### ISSUE THREAD

**Issue by ModdedGamers** [famiu/feline.nvim#50] opened 2021-09-06 14:41 UTC
**Neovim version**
NVIM v0.6.0-dev+210-g6751d6254

**Feline version**
ee74b0c6762d186a42da5bc0f53bbab0fca6a277

**Describe the bug**
When opening a file, feline crashes. 

**To Reproduce**
1. Download my custom config
2. Run neovim using my config
3. Open any file
4. It should crash.

**Expected behavior**
I expected it to not crash.

**Does this error occur in the minimal init file?**
No it does not.

**Additional context**
I do my config in a weird way(see below for my feline config file), and that may be the issue.

[feline.lua](https://ufile.io/jbrkpyzh)
^ Try loading this file in nvim and see if the problem occurs then.

**Comment by famiu** [comment] 2021-09-06 14:55
could you put your config in a pastebin instead of that website, it's not working for me

**Comment by ModdedGamers** [comment] 2021-09-06 14:58
https://hastebin.com/atelolehun.lua

**Comment by famiu** [comment] 2021-09-06 14:59
Does the issue still occur if you remove the timer component?

**Comment by ModdedGamers** [comment] 2021-09-06 15:03
Yes it does

**Comment by famiu** [comment] 2021-09-06 15:06
I can't try out your config right now, but can you try putting your config inside the minimal_init.lua file and see if it works? I'm wondering if an external plugin is interfering with the config

**Comment by ModdedGamers** [comment] 2021-09-06 15:12
ok, it's an issue with how i define my config. when I put my config into the minimal init, it crashes.

**Comment by famiu** [comment] 2021-09-06 15:14
> ok, it's an issue with how i define my config. when I put my config into the minimal init, it crashes.

Hmm, one thing I noticed is that you're defining fg and bg twice, once through the colors table and once through the default_fg and default_bg options. Maybe try removing one of them?

**Comment by ModdedGamers** [comment] 2021-09-06 15:18
That does not fix the problem.

**Comment by famiu** [comment] 2021-09-06 16:08
> That does not fix the problem.

Okay so, 3 things:

1. While defining some of the colors, you didn't put a '#' before the RGB hex
2. You didn't initialize the 'bufnames' table of the force_inactive property
3. vim.loop.new_timer is a function, so you have to call it. But afaik, timers can't return values so you still can't use it as a component, so remove that component altogether.
4. Although this isn't going to cause an error, you still defined fg and bg twice as I mentioned earlier, so remove that too.

After doing all that, Feline should work

**Comment by ModdedGamers** [comment] 2021-09-06 19:06
The problem was that I did not initialize the bufnames table. I fixed everything else though, so that should help. and I tested the `vim.loop.new_timer` loop before I implemented it, and it worked. So IDK, maybe different behavior in 0.6.

**Comment by famiu** [comment] 2021-09-06 19:09
> The problem was that I did not initialize the bufnames table. I fixed everything else though, so that should help. and I tested the `vim.loop.new_timer` loop before I implemented it, and it worked. So IDK, maybe different behavior in 0.6.

So I assume the issue is fixed for you? In that case, you should close this

**Closed** 2021-09-06 19:53 UTC
Labels: bug
