### ISSUE TITLE
How do I create shortline?

### ISSUE THREAD

**Issue by siduck76** [famiu/feline.nvim#70] opened 2021-09-14 17:46 UTC
Hi @famiu great plugin :D . Been using it for a while now , galaxyline had a separate section for shortline , how do I do this with feline? 

For example some components arent visible if the buffer's width is small 

![image](https://user-images.githubusercontent.com/59060246/133307746-29789eba-0287-4cd4-805f-d20c0872515b.png)

**Comment by famiu** [comment] 2021-09-15 13:47
Just use the `enabled` component value. Like this:

```
-- Enable only when the window width is above 80
enabled = function(winid)
    return vim.api.nvim_win_get_width(winid) > 80
end
```

**Comment by famiu** [comment] 2021-09-15 17:48
I'm wondering if I should add a component option that automatically handles that for the user, so they can use `enabled` for other stuff without cluttering it with window size checks.

**Comment by ram02z** [comment] 2021-09-15 18:03
For what it is worth, I am not bothered by the "clutter" it causes in the enabled section, since most of the logic I use in there is quite basic. If you do think it should a component option. I feel like the discussion about truncation in https://github.com/famiu/feline.nvim/pull/65 should be considered too.

**Comment by famiu** [comment] 2021-09-15 18:19
> For what it is worth, I am not bothered by the "clutter" it causes in the enabled section, since most of the logic I use in there is quite basic. If you do think it should be a component option. I feel like the discussion about truncation in #65 should be considered too. The main part from the discussion I think would be interesting to implement is a priority system, where components are disabled depending on the remaining window width, however, a simple use of `nvim_win_get_width` as shown above will basically give the same result.

That's true. Overall there is no good reason to add yet another component option for something so basic. So I'll close this issue now.

**Closed by famiu** 2021-09-15 18:19 UTC

**Comment by siduck76** [comment] 2021-09-24 07:32
> Just use the `enabled` component value. Like this:
> 
> ```lua
> -- Enable only when the window width is above 80
> enabled = function(winid)
>     return vim.api.nvim_win_get_width(winid) > 80
> end
> ```

i dont get it! How do I add it on my component?

![image](https://user-images.githubusercontent.com/59060246/134635970-47bdd160-e794-438b-b65a-0b11bf1378a4.png)

**Comment by famiu** [comment] 2021-09-24 07:44
> > Just use the `enabled` component value. Like this:
> > ```lua
> > -- Enable only when the window width is above 80
> > enabled = function(winid)
> >     return vim.api.nvim_win_get_width(winid) > 80
> > end
> > ```
> 
> i dont get it! How do I add it on my component?
> 
> ![image](https://user-images.githubusercontent.com/59060246/134636053-5bb511d5-4888-4f61-affa-c2d196d6cecd.png)

Put it inside the component after the provider

**Comment by siduck76** [comment] 2021-09-26 02:00
> > > Just use the `enabled` component value. Like this:
> > > ```lua
> > > -- Enable only when the window width is above 80
> > > enabled = function(winid)
> > >     return vim.api.nvim_win_get_width(winid) > 80
> > > end
> > > ```
> > 
> > 
> > i dont get it! How do I add it on my component?
> > ![image](https://user-images.githubusercontent.com/59060246/134636053-5bb511d5-4888-4f61-affa-c2d196d6cecd.png)
> 
> Put it inside the component after the provider

oh but what argument do I give it? enabled(..?)

**Comment by famiu** [comment] 2021-09-26 02:19
> > > > Just use the `enabled` component value. Like this:
> > > > ```lua
> > > > -- Enable only when the window width is above 80
> > > > enabled = function(winid)
> > > >     return vim.api.nvim_win_get_width(winid) > 80
> > > > end
> > > > ```
> > > 
> > > 
> > > i dont get it! How do I add it on my component?
> > > ![image](https://user-images.githubusercontent.com/59060246/134636053-5bb511d5-4888-4f61-affa-c2d196d6cecd.png)
> > 
> > 
> > Put it inside the component after the provider
> 
> oh but what argument do I give it? enabled(..?)

winid

**Comment by siduck76** [comment] 2021-09-26 02:38
enabled(vim.fn.win_getid) ?

**Comment by Joakker** [comment] 2021-09-26 02:46
Do something like this
```lua
components.active[1][1] = {
  provider = " Nvim ",
  enabled = function(winid)
    return vim.api.nvim_win_get_width(winid) > 80
  end
}

**Comment by siduck76** [comment] 2021-09-26 02:53
> enabled(vim.fn.win_getid) ?



> ```lua
>  enabled = function(winid)
>     return vim.api.nvim_win_get_width(winid) > 80
>   end
> ```

thanks this worked!

**Comment by siduck76** [comment] 2021-09-26 03:05
@Joakker removing a specific component breaks the highlights of the statusline ( only bg color ) 

My component 
```
components.active[1][3] = {
   provider = function()
      local dir_name = vim.fn.fnamemodify(vim.fn.getcwd(), ":t")
      return "  " .. dir_name .. " "
   end,

   enabled = function(winid)
      return vim.api.nvim_win_get_width(winid) > 80
   end,

   hl = {
      fg = colors.grey_fg2,
      bg = colors.lightbg2,
   },
}
```

**Comment by siduck76** [comment] 2021-09-26 03:05
before : 
![image](https://user-images.githubusercontent.com/59060246/134791918-4b4726d3-04af-43bd-b34d-d499c32762a2.png)

after : 

![image](https://user-images.githubusercontent.com/59060246/134791923-d883614f-f7db-4024-b0f5-d99a88620857.png)

**Comment by famiu** [comment] 2021-09-26 04:07
@siduck76 can you try using the latest commit in develop and see if that fixes your issue?

**Comment by siduck76** [comment] 2021-09-26 04:30
@famiu yep it works now.

**Comment by siduck76** [comment] 2021-09-26 14:34
@famiu after the recent commits , my inactive statusline no longer looks like a line :c 

![image](https://user-images.githubusercontent.com/59060246/134812215-fee12815-939e-4fe4-87be-ab571f0132ce.png)

As you can see the inactive statuslines are just thin lines here : 

This worked before :+1: 

```
hi StatuslineNC gui=underline guibg=NONE
```

**Comment by famiu** [comment] 2021-09-26 14:39
> @famiu after the recent commits , my inactive statusline no longer looks like a line :c
> 
> ![image](https://user-images.githubusercontent.com/59060246/134812215-fee12815-939e-4fe4-87be-ab571f0132ce.png)
> 
> As you can see the inactive statuslines are just thin lines here :
> 
> This worked before :
> 
> ```
> hi StatuslineNC gui=underline guibg=NONE
> ```

See https://github.com/famiu/feline.nvim/blob/master/USAGE.md#thin-line-for-horizontal-splits

**Comment by siduck76** [comment] 2021-09-26 15:31
> > @famiu after the recent commits , my inactive statusline no longer looks like a line :c
> > ![image](https://user-images.githubusercontent.com/59060246/134812215-fee12815-939e-4fe4-87be-ab571f0132ce.png)
> > As you can see the inactive statuslines are just thin lines here :
> > This worked before :
> > ```
> > hi StatuslineNC gui=underline guibg=NONE
> > ```
> 
> See https://github.com/famiu/feline.nvim/blob/master/USAGE.md#thin-line-for-horizontal-splits

oh that looks long! . My highlight did work on galaxyline and feline too , is there any shorter version of it or such? D:

**Comment by famiu** [comment] 2021-09-26 15:33
> > > @famiu after the recent commits , my inactive statusline no longer looks like a line :c
> > > ![image](https://user-images.githubusercontent.com/59060246/134812215-fee12815-939e-4fe4-87be-ab571f0132ce.png)
> > > As you can see the inactive statuslines are just thin lines here :
> > > This worked before :
> > > ```
> > > hi StatuslineNC gui=underline guibg=NONE
> > > ```
> > 
> > 
> > See https://github.com/famiu/feline.nvim/blob/master/USAGE.md#thin-line-for-horizontal-splits
> 
> oh that looks long! . My highlight did work on galaxyline and feline too , is there any shorter version of it or such? D:

What's the last commit that works for you?

**Comment by siduck76** [comment] 2021-09-26 15:37
> > > > @famiu after the recent commits , my inactive statusline no longer looks like a line :c
> > > > ![image](https://user-images.githubusercontent.com/59060246/134812215-fee12815-939e-4fe4-87be-ab571f0132ce.png)
> > > > As you can see the inactive statuslines are just thin lines here :
> > > > This worked before :
> > > > ```
> > > > hi StatuslineNC gui=underline guibg=NONE
> > > > ```
> > > 
> > > 
> > > See https://github.com/famiu/feline.nvim/blob/master/USAGE.md#thin-line-for-horizontal-splits
> > 
> > 
> > oh that looks long! . My highlight did work on galaxyline and feline too , is there any shorter version of it or such? D:
> 
> What's the last commit that works for you?

It was working fine yesterday so I assume these commits might've caused the behaviour : 

![image](https://user-images.githubusercontent.com/59060246/134814536-01514cc5-f54d-4820-969b-5fe7125a6520.png)

**Comment by famiu** [comment] 2021-09-26 15:52
> > > > > @famiu after the recent commits , my inactive statusline no longer looks like a line :c
> > > > > ![image](https://user-images.githubusercontent.com/59060246/134812215-fee12815-939e-4fe4-87be-ab571f0132ce.png)
> > > > > As you can see the inactive statuslines are just thin lines here :
> > > > > This worked before :
> > > > > ```
> > > > > hi StatuslineNC gui=underline guibg=NONE
> > > > > ```
> > > > 
> > > > 
> > > > See https://github.com/famiu/feline.nvim/blob/master/USAGE.md#thin-line-for-horizontal-splits
> > > 
> > > 
> > > oh that looks long! . My highlight did work on galaxyline and feline too , is there any shorter version of it or such? D:
> > 
> > 
> > What's the last commit that works for you?
> 
> It was working fine yesterday so I assume these commits might've caused the behaviour :
> 
> ![image](https://user-images.githubusercontent.com/59060246/134814536-01514cc5-f54d-4820-969b-5fe7125a6520.png)

The code you shared doesn't work for me even before those commits. So the way mentioned in the README is the only way, and I don't plan to make it otherwise.

**Comment by siduck76** [comment] 2021-09-26 16:36
> > > > > > @famiu after the recent commits , my inactive statusline no longer looks like a line :c
> > > > > > ![image](https://user-images.githubusercontent.com/59060246/134812215-fee12815-939e-4fe4-87be-ab571f0132ce.png)
> > > > > > As you can see the inactive statuslines are just thin lines here :
> > > > > > This worked before :
> > > > > > ```
> > > > > > hi StatuslineNC gui=underline guibg=NONE
> > > > > > ```
> > > > > 
> > > > > 
> > > > > See https://github.com/famiu/feline.nvim/blob/master/USAGE.md#thin-line-for-horizontal-splits
> > > > 
> > > > 
> > > > oh that looks long! . My highlight did work on galaxyline and feline too , is there any shorter version of it or such? D:
> > > 
> > > 
> > > What's the last commit that works for you?
> > 
> > 
> > It was working fine yesterday so I assume these commits might've caused the behaviour :
> > ![image](https://user-images.githubusercontent.com/59060246/134814536-01514cc5-f54d-4820-969b-5fe7125a6520.png)
> 
> The code you shared doesn't work for me even before those commits. So the way mentioned in the README is the only way, and I don't plan to make it otherwise.

The way mentioned in the README doesnt work here either 

![image](https://user-images.githubusercontent.com/59060246/134816229-dbb29e22-a842-411f-93ca-d6c6df93e885.png)

**Comment by famiu** [comment] 2021-09-26 16:40
> > > > > > > @famiu after the recent commits , my inactive statusline no longer looks like a line :c
> > > > > > > ![image](https://user-images.githubusercontent.com/59060246/134812215-fee12815-939e-4fe4-87be-ab571f0132ce.png)
> > > > > > > As you can see the inactive statuslines are just thin lines here :
> > > > > > > This worked before :
> > > > > > > ```
> > > > > > > hi StatuslineNC gui=underline guibg=NONE
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > See https://github.com/famiu/feline.nvim/blob/master/USAGE.md#thin-line-for-horizontal-splits
> > > > > 
> > > > > 
> > > > > oh that looks long! . My highlight did work on galaxyline and feline too , is there any shorter version of it or such? D:
> > > > 
> > > > 
> > > > What's the last commit that works for you?
> > > 
> > > 
> > > It was working fine yesterday so I assume these commits might've caused the behaviour :
> > > ![image](https://user-images.githubusercontent.com/59060246/134814536-01514cc5-f54d-4820-969b-5fe7125a6520.png)
> > 
> > 
> > The code you shared doesn't work for me even before those commits. So the way mentioned in the README is the only way, and I don't plan to make it otherwise.
> 
> The way mentioned in the README doesnt work here either
> 
> ![image](https://user-images.githubusercontent.com/59060246/134816229-dbb29e22-a842-411f-93ca-d6c6df93e885.png)

please make a new issue for it and provide your full config and the minimal init to reproduce it as well in the new issue
