### ISSUE TITLE
How to make the filename showed in status bar unique

### ISSUE THREAD

**Issue by pianocomposer321** [famiu/feline.nvim#13] opened 2021-05-07 17:56 UTC
First of all, thank you so much for sharing this plugin with the Neovim community. I wanted to try out galaxyline.nvim, but I found it very hard to configure. With this plugin, I just copy-pasted one of the included configs and changed it till I like it. It's the perfect combination of power and ease of use. So thanks.

Now for my issue. Consider the following screenshot:

![unique_filename](https://user-images.githubusercontent.com/54072354/117488383-f72b4b00-af31-11eb-99b0-74309e21ec95.png)

Those two splits clearly contain different files, but they are both named `init.lua`, so the default `file_info` provider shows them as the same (because it uses `expand("%:t")` instead of `expand("%")`). To be clear, I like this as the default, because the status line would get cluttered very quickly if it used the fully qualified path by default. But I am wondering if you have any ideas for how to avoid this in my personal config. I'm thinking like only show the tail (`%:t`) normally, but if there are two buffers that have the same filename, add on the names of their parent folders until they are unique. For example, `projects/example1/init.lua` and `projects/example2/init.lua` would show only `example1/init.lua` and `example2/init.lua`, but `example1/lua/init.lua` and `example2/lua/init.lua` would have to show their entire paths because going up one level wouldn't make them unique.

Do you have any idea how to go about doing this?

Possibly tangentially related: https://github.com/famiu/feline.nvim/issues/6

**Comment by pianocomposer321** [comment] 2021-05-07 19:19
@famiu, ok, I actually have started working on something (not 100% sure it will work, but I'm trying). If it does work, do you want it merged into the main plugin? And if so, how?

It might be simpler if I just copy+paste the function that I use into here and you figure out what file it should go in and how to modify the codebase yourself...I haven't done many pull requests and I don't trust myself not to mess something up.

**Comment by famiu** [comment] 2021-05-07 19:22
> @famiu, ok, I actually have started working on something (not 100% sure it will work, but I'm trying). If it does work, do you want it merged into the main plugin? And if so, how?
> 
> It might be simpler if I just copy+paste the function that I use into here and you figure out what file it should go in and how to modify the codebase yourself...I haven't done many pull requests and I don't trust myself not to mess something up.
> 
Yeah sure, you can do that

**Comment by cloggier** [comment] 2021-05-08 06:55
How about a provider displaying path relative to git repo root?

**Comment by famiu** [comment] 2021-05-08 09:54
> How about a provider displaying path relative to git repo root?

The two files could be in different git repos and have the same relative path from the root, in which case they'd still have the same name.

**Comment by pianocomposer321** [comment] 2021-05-08 15:13
> How about a provider displaying path relative to git repo root?

Yeah, I agree with @famiu. I'm not saying that that's a bad idea necessarily, but it doesn't solve this particular issue. Doesn't seem like it should be too difficult to implement though.

To further clarify, what the above code does is compare the currently open file with all the other listed buffers, and adds on the name of its parent directories until it's different from all the rest.

That said, if either of you have ideas for how it could be improved (either the method or the implementation), please let me know. Like I said, I know that my code is far from perfect :wink:.

@famiu should this be closed, since I came up with a solution for myself? Or do you want it left open until you add something to the main codebase yourself?

**Comment by famiu** [comment] 2021-05-08 18:09
> @famiu should this be closed, since I came up with a solution for myself? Or do you want it left open until you add something to the main codebase yourself?
>
I'll keep it open until I add something to the main codebase

**Comment by famiu** [comment] 2021-05-22 11:47
@pianocomposer321 Sorry for being so late (was busy the last few days) but I finally implemented a way to further configure the `file_info` provider to show unique filenames, but also added many other configuration options. Read the README in case you're interested.

**Comment by cloggier** [comment] 2021-05-22 16:43
@famiu Just pulled latest update, great stuff! One thing I would actually like to see is an option to set path related to git repo's root.

I was using something like this:

```lua
local ok, git_dir = pcall(a.nvim_buf_get_var, buf.bufnr, "git_dir") -- vim-fugitive

if ok and git_dir then
  -- Path relative to git repo's root.
  local root = vim.fn.fnamemodify(git_dir, ":h")
  local path = vim.fn.fnamemodify(buf.name, ":p:h")
  local repo_path, _ = path:gsub(root, "")

  return #repo_path > 0 and repo_path:gsub("/", "", 1) .. "/" or ""
else
  -- Parent directory.
  local filename = vim.fn.fnamemodify(buf.name, ":t")

  if filename ~= "" then
    return vim.fn.fnamemodify(buf.name, ":p:h:t") .. "/"
  end
end
```

to get path from git repo or just one extra directory as fallback in case we are not in repo.

What do you think about another parameter to that setting?

**Comment by cloggier** [comment] 2021-05-22 16:44
Ah, I think `relative` can actually take care of it since rooter changes path for me to git repo's root.

**Comment by famiu** [comment] 2021-05-22 18:00
> Ah, I think `relative` can actually take care of it since rooter changes path for me to git repo's root.

Yes, that's precisely why I added it

**Comment by pianocomposer321** [comment] 2021-05-22 19:21
I'm getting an error:
![error](https://user-images.githubusercontent.com/54072354/119238554-a0fd0100-bb08-11eb-993c-e36e070b4e6d.png)

It's quite possible that I'm using the option wrong...I had a hard time figuring it out from the README. Here's the relevant part of my config:

```lua
            provider = 'file_info',
            type = 'unique',
            hl = {
                fg = colors.blue,
                style = 'bold'
            },
            left_sep = ' '

```

**Comment by famiu** [comment] 2021-05-23 04:52
> I'm getting an error:
> ![error](https://user-images.githubusercontent.com/54072354/119238554-a0fd0100-bb08-11eb-993c-e36e070b4e6d.png)
> 
> It's quite possible that I'm using the option wrong...I had a hard time figuring it out from the README. Here's the relevant part of my config:
> 
> ```lua
>             provider = 'file_info',
>             type = 'unique',
>             hl = {
>                 fg = colors.blue,
>                 style = 'bold'
>             },
>             left_sep = ' '
> ```

Did you try using the minimal_init.lua provided by Feline? If not, just use
`curl -fLO https://raw.githubusercontent.com/neovim/nvim-lspconfig/master/test/minimal_init.lua`
To download it, and then edit the config (but make as few edits as possible, just enough to reproduce your issue), and after you're done with the edits, load the config using:
`nvim -u minimal_init.lua`
Then see if the issue still persists.

**Comment by pianocomposer321** [comment] 2021-05-23 19:21
> > I'm getting an error:
> > ![error](https://user-images.githubusercontent.com/54072354/119238554-a0fd0100-bb08-11eb-993c-e36e070b4e6d.png)
> > It's quite possible that I'm using the option wrong...I had a hard time figuring it out from the README. Here's the relevant part of my config:
> > ```lua
> >             provider = 'file_info',
> >             type = 'unique',
> >             hl = {
> >                 fg = colors.blue,
> >                 style = 'bold'
> >             },
> >             left_sep = ' '
> > ```
> 
> Did you try using the minimal_init.lua provided by Feline? If not, just use
> `curl -fLO https://raw.githubusercontent.com/neovim/nvim-lspconfig/master/test/minimal_init.lua`
> To download it, and then edit the config (but make as few edits as possible, just enough to reproduce your issue), and after you're done with the edits, load the config using:
> `nvim -u minimal_init.lua`
> Then see if the issue still persists.

Ahem, shouldn't that be https://raw.githubusercontent.com/famiu/feline.nvim/master/minimal_init.lua? You linked to the one for lsp_config :rofl:.

Anyway, I'll try it with the right one and get back with you.

**Comment by pianocomposer321** [comment] 2021-05-23 19:31
Here's the minimal reproducing init.lua:

<details>
<summary>minimal_init.lua</summary>

```lua
-- install packer
local fn = vim.fn
local cmd = vim.cmd

local install_path = '/tmp/nvim/site/pack/packer/start/packer.nvim'

cmd('set packpath=/tmp/nvim/site')

local function load_plugins()
    require('packer').startup {
        function(use)
            use 'wbthomason/packer.nvim'
            use {
                'famiu/feline.nvim',
                requires = {
                    {
                        'lewis6991/gitsigns.nvim',
                        requires = { 'nvim-lua/plenary.nvim' },
                        config = function()
                            require('gitsigns').setup()
                        end
                    },
                    'kyazdani42/nvim-web-devicons'
                }
            }
        end,

        config = {
            package_root = '/tmp/nvim/site/pack',
            git = {
                clone_timeout = -1
            }
        }
    }
end

_G.load_config = function()
    cmd('set termguicolors')

    -- Replace this part of the config with whatever Feline configuration you're using
    require('feline').setup {
	components = {left = {active = {
	    provider = 'file_info',
	    type = 'unique'
	}}}
    }
end

if fn.isdirectory(install_path) == 0 then
    fn.system({'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path})
end

load_plugins()
require('packer').sync()
cmd('autocmd User PackerComplete ++once lua load_config()')
```
</details>

**Comment by famiu** [comment] 2021-05-24 03:43
> > > I'm getting an error:
> > > ![error](https://user-images.githubusercontent.com/54072354/119238554-a0fd0100-bb08-11eb-993c-e36e070b4e6d.png)
> > > It's quite possible that I'm using the option wrong...I had a hard time figuring it out from the README. Here's the relevant part of my config:
> > > ```lua
> > >             provider = 'file_info',
> > >             type = 'unique',
> > >             hl = {
> > >                 fg = colors.blue,
> > >                 style = 'bold'
> > >             },
> > >             left_sep = ' '
> > > ```
> > 
> > 
> > Did you try using the minimal_init.lua provided by Feline? If not, just use
> > `curl -fLO https://raw.githubusercontent.com/neovim/nvim-lspconfig/master/test/minimal_init.lua`
> > To download it, and then edit the config (but make as few edits as possible, just enough to reproduce your issue), and after you're done with the edits, load the config using:
> > `nvim -u minimal_init.lua`
> > Then see if the issue still persists.
> 
> Ahem, shouldn't that be https://raw.githubusercontent.com/famiu/feline.nvim/master/minimal_init.lua? You linked to the one for lsp_config rofl.
> 
> Anyway, I'll try it with the right one and get back with you.

Oops. Sorry, I got the wrong link 🤦🏼

**Comment by famiu** [comment] 2021-05-24 04:56
> Here's the minimal reproducing init.lua:
> minimal_init.lua
> 
> ```lua
> -- install packer
> local fn = vim.fn
> local cmd = vim.cmd
> 
> local install_path = '/tmp/nvim/site/pack/packer/start/packer.nvim'
> 
> cmd('set packpath=/tmp/nvim/site')
> 
> local function load_plugins()
>     require('packer').startup {
>         function(use)
>             use 'wbthomason/packer.nvim'
>             use {
>                 'famiu/feline.nvim',
>                 requires = {
>                     {
>                         'lewis6991/gitsigns.nvim',
>                         requires = { 'nvim-lua/plenary.nvim' },
>                         config = function()
>                             require('gitsigns').setup()
>                         end
>                     },
>                     'kyazdani42/nvim-web-devicons'
>                 }
>             }
>         end,
> 
>         config = {
>             package_root = '/tmp/nvim/site/pack',
>             git = {
>                 clone_timeout = -1
>             }
>         }
>     }
> end
> 
> _G.load_config = function()
>     cmd('set termguicolors')
> 
>     -- Replace this part of the config with whatever Feline configuration you're using
>     require('feline').setup {
> 	components = {left = {active = {
> 	    provider = 'file_info',
> 	    type = 'unique'
> 	}}}
>     }
> end
> 
> if fn.isdirectory(install_path) == 0 then
>     fn.system({'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path})
> end
> 
> load_plugins()
> require('packer').sync()
> cmd('autocmd User PackerComplete ++once lua load_config()')
> ```

Did you run it with `nvim -u minimal_init.lua`? Because the configuration you provided in feline's setup is wrong. It should be:
```lua
require('feline').setup {
    components = {
        left = {
            active = {
                {
                    provider = 'file_info',
                    type = 'unique'
                }
            }
        }
    }
}
```

And I also updated some things in Feline as well. So fix your config and try again. And if it still shows the error, tell me what the error is.

**Comment by pianocomposer321** [comment] 2021-05-24 14:06
> > Here's the minimal reproducing init.lua:
> > minimal_init.lua
> > ```lua
> > -- install packer
> > local fn = vim.fn
> > local cmd = vim.cmd
> > 
> > local install_path = '/tmp/nvim/site/pack/packer/start/packer.nvim'
> > 
> > cmd('set packpath=/tmp/nvim/site')
> > 
> > local function load_plugins()
> >     require('packer').startup {
> >         function(use)
> >             use 'wbthomason/packer.nvim'
> >             use {
> >                 'famiu/feline.nvim',
> >                 requires = {
> >                     {
> >                         'lewis6991/gitsigns.nvim',
> >                         requires = { 'nvim-lua/plenary.nvim' },
> >                         config = function()
> >                             require('gitsigns').setup()
> >                         end
> >                     },
> >                     'kyazdani42/nvim-web-devicons'
> >                 }
> >             }
> >         end,
> > 
> >         config = {
> >             package_root = '/tmp/nvim/site/pack',
> >             git = {
> >                 clone_timeout = -1
> >             }
> >         }
> >     }
> > end
> > 
> > _G.load_config = function()
> >     cmd('set termguicolors')
> > 
> >     -- Replace this part of the config with whatever Feline configuration you're using
> >     require('feline').setup {
> > 	components = {left = {active = {
> > 	    provider = 'file_info',
> > 	    type = 'unique'
> > 	}}}
> >     }
> > end
> > 
> > if fn.isdirectory(install_path) == 0 then
> >     fn.system({'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path})
> > end
> > 
> > load_plugins()
> > require('packer').sync()
> > cmd('autocmd User PackerComplete ++once lua load_config()')
> > ```
> 
> Did you run it with `nvim -u minimal_init.lua`? Because the configuration you provided in feline's setup is wrong. It should be:
> 
> ```lua
> require('feline').setup {
>     components = {
>         left = {
>             active = {
>                 {
>                     provider = 'file_info',
>                     type = 'unique'
>                 }
>             }
>         }
>     }
> }
> ```
> 
> And I also updated some things in Feline as well. So fix your config and try again. And if it still shows the error, tell me what the error is.

I think that's the same as what I have except mine doesn't have the indentation. But anyway, I'll update and see if that fixes it.

**Comment by pianocomposer321** [comment] 2021-05-24 14:07
Oh, nvm, I missed one pair of braces, you're right. I'll fix that as well.

**Comment by pianocomposer321** [comment] 2021-05-24 14:20
After updating feline, the error does go away. I think this is fixed, so unless you have something else to add @famiu, I guess this can be closed now.

**Comment by famiu** [comment] 2021-05-24 16:52
Alright, I'm closing the issue.

**Closed by famiu** 2021-05-24 16:52 UTC
